/* eslint-disable @next/next/no-typos */
import { getSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import Banner from "../components/Banner";
import Header from "../components/Header";
import ProductFeed from "../components/ProductFeed";
export default function Home({ product }) {
    return (
        <div className="bg-gray-100 ">
            <Head>
                <title>Amazon.com Spend less.Smile</title>
                <link rel="icon" href="/favicon-16x16.png" />
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <Header />

            <main className="max-w-screen-xl mx-auto ">
                {/* Banner */}
                <Banner />
                {/* productfeed */}
                <ProductFeed product={product} />
            </main>
        </div>
    );
}

export async function getServerSideProps(context) {
    const product = await fetch("https://fakestoreapi.com/products").then(
        (res) => res.json()
    );
    const session = await getSession(context);

    return {
        props: {
            product,
            session,
        },
    };
}
